version: 2

models:
  - name: stg_energy_facts
    description: Table from the Global sustainable energy dataset that displays the country energy facts.

  - name: stg_dim_electricity
    description: Join table displaying energy facts and electricity facts
