version: 2

models:
  - name: stg_energy_facts
    description: Table from the Global sustainable energy dataset that displays the country energy facts.

  - name: country_electricity_dim
    description: Join table displaying countries and their electricity facts
